"""Send iMessages via AppleScript.

Security-critical: the body of a reply is generated by Claude and contains
arbitrary text. We MUST NOT interpolate that text into an AppleScript source
string — quotes, backslashes, or null bytes inside the body could escape the
literal and execute attacker-controlled script.

The safe pattern:

  ``osascript -e SCRIPT -- handle body``

``osascript``'s ``--`` separator passes the following arguments to the
AppleScript's ``on run argv`` handler. They arrive as already-parsed string
values, NOT as shell tokens or AppleScript source. UTF-8 is handled
correctly end-to-end (osascript uses NSString internally for argv).

The handle is also validated against a strict regex BEFORE invocation so a
malicious sender can't smuggle a payload through their own handle. The body
is run through ``_strip_display_attacks`` and length-capped first.
"""

from __future__ import annotations

import logging
import re
import subprocess
from dataclasses import dataclass
from typing import Final

logger = logging.getLogger(__name__)

# Phone in E.164 form, or an Apple ID email. Anything else is a hard reject.
# We are deliberately strict to keep the attack surface for handle-string
# tricks (zero-width chars, RTL overrides, etc.) tiny.
_E164_RE: Final = re.compile(r"^\+[1-9]\d{6,14}$")
_EMAIL_RE: Final = re.compile(r"^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$")

# Hard cap on reply length. Both a defense-in-depth measure (limits any
# AppleScript-payload smuggling) and a UX choice (iMessage truncates very
# long messages anyway).
MAX_REPLY_BYTES: Final = 8000

# Characters that change visual rendering vs. raw text. Stripped from
# outgoing bodies so what the recipient sees matches what we logged and
# what Claude generated.
_BIDI_CHARS: Final = "‪‫‬‭‮⁦⁧⁨⁩"
_ZERO_WIDTH_CHARS: Final = "​‌‍⁠﻿"
_DISPLAY_ATTACK_TABLE: Final = str.maketrans(
    "", "", _BIDI_CHARS + _ZERO_WIDTH_CHARS
)


def _strip_display_attacks(body: str) -> str:
    """Remove BiDi format chars, zero-width chars, and C0/C1 controls.

    These can make Messages render text differently from what we logged,
    creating a "what you see is not what we sent" gap that's awkward at
    best and an audit/forensics gap at worst. Tab, newline, and carriage
    return are preserved.
    """
    cleaned = body.translate(_DISPLAY_ATTACK_TABLE)
    # Strip C0 controls (0x00-0x1F) except \t \n \r, and C1 controls (0x80-0x9F).
    out_chars = []
    for ch in cleaned:
        cp = ord(ch)
        if cp < 0x20 and ch not in "\t\n\r":
            continue
        if 0x80 <= cp <= 0x9F:
            continue
        out_chars.append(ch)
    return "".join(out_chars)


class HandleError(ValueError):
    """Handle didn't match an allowed format. Refuse to send."""


class SendError(RuntimeError):
    """osascript reported failure."""


@dataclass(frozen=True)
class SendRequest:
    handle: str       # validated by validate_handle() before construction
    body: str         # capped at MAX_REPLY_BYTES; may be truncated


def validate_handle(handle: str) -> str:
    """Validate and normalize a handle. Raises HandleError on bad input.

    Returns the normalized form (E.164 phones unchanged, emails lower-cased).
    Normalization is the safe baseline for allowlist comparison; callers
    should always compare against the validated form.
    """
    if not isinstance(handle, str):
        raise HandleError(f"handle must be str, got {type(handle).__name__}")
    candidate = handle.strip()
    if not candidate:
        raise HandleError("empty handle")
    if _E164_RE.match(candidate):
        return candidate
    if _EMAIL_RE.match(candidate):
        return candidate.lower()
    raise HandleError(f"handle does not match phone or email pattern: {candidate!r}")


def _truncate(body: str) -> str:
    """Truncate a reply to MAX_REPLY_BYTES, byte-wise, on a UTF-8 boundary."""
    encoded = body.encode("utf-8")
    if len(encoded) <= MAX_REPLY_BYTES:
        return body
    # Find a safe cut point that doesn't split a multibyte sequence.
    cut = MAX_REPLY_BYTES
    while cut > 0 and (encoded[cut] & 0xC0) == 0x80:
        cut -= 1
    return encoded[:cut].decode("utf-8", errors="ignore") + "\n…[truncated]"


# Absolute path to osascript. Pinning to /usr/bin/osascript prevents a
# ``$PATH`` shadow (e.g. ~/bin/osascript) from intercepting the send path.
# Verified by ``_preflight()`` at daemon startup.
_OSASCRIPT_BIN: Final = "/usr/bin/osascript"

# AppleScript that receives ``handle`` and ``messageText`` directly as
# positional arguments. argv values are decoded by osascript as UTF-8
# NSStrings — no shell, no ``do shell script``, no Mac-Roman conversion
# (which is what ``do shell script "cat"`` would impose). This is the
# correct shape for safe + encoding-correct send.
_APPLESCRIPT: Final = r'''
on run argv
    set targetHandle to item 1 of argv
    set messageText to item 2 of argv
    tell application "Messages"
        set targetService to 1st service whose service type = iMessage
        set targetBuddy to buddy targetHandle of targetService
        send messageText to targetBuddy
    end tell
end run
'''


def send(request: SendRequest, *, dry_run: bool = False) -> None:
    """Send an iMessage reply.

    Raises:
      HandleError on invalid handle (won't happen if SendRequest was built
        via validate_handle, but defense-in-depth).
      SendError on osascript failure.
    """
    # Re-validate even though SendRequest is meant to carry a validated handle.
    handle = validate_handle(request.handle)
    body = _strip_display_attacks(request.body or "")
    body = _truncate(body)
    if not body.strip():
        logger.debug("Refusing to send empty body to %s", _redact_handle(handle))
        return

    if dry_run:
        logger.info("DRY RUN — would send %d bytes to %s",
                    len(body.encode("utf-8")), _redact_handle(handle))
        return

    # ``osascript -e SCRIPT -- ARG1 ARG2`` passes ARG1/ARG2 to the script's
    # ``on run argv`` handler as already-parsed UTF-8 strings. NO shell
    # interpretation, NO AppleScript source-level interpolation. Each arg
    # is bounded in size by argv limits but our caps (8KB body + tight
    # handle regex) keep this comfortably under the OS limit.
    proc = subprocess.run(
        [_OSASCRIPT_BIN, "-e", _APPLESCRIPT, "--", handle, body],
        capture_output=True,
        text=True,
        timeout=15,
    )

    if proc.returncode != 0:
        stderr = (proc.stderr or "").strip().splitlines()[-1] if proc.stderr else ""
        raise SendError(f"osascript exit {proc.returncode}: {stderr}")
    logger.info(
        "sent %d bytes to %s",
        len(body.encode("utf-8")),
        _redact_handle(handle),
    )


def _redact_handle(handle: str) -> str:
    """Reduce a handle to a non-PII-leaking form for logs."""
    if "@" in handle:
        local, _, domain = handle.partition("@")
        return f"{local[:2]}***@{domain}"
    # Phone: keep country code + last 2 digits.
    if len(handle) > 5:
        return f"{handle[:3]}***{handle[-2:]}"
    return "***"
